Add a method to copy the entire matrix.
finalfusion/finalfusion-python pull request #11
Opened 2019-06-04 17:46 UTC by sebpuetz

Not sure if there's a way to handle the `QuantizedArray` case more gracefully.

Is this what you had in mind in #5?

I think the matrix by itself is pretty useless, so adding a method to get the vocab in the Python module would be up next. Or at least adding a way to get the length of the vocab, so it's possible to figure out the offset into the matrix where the subword embeddings start.

2019-06-04 18:06 UTC, danieldk requested changes
Looks good. Several questions/comments:

* It would be nicer if this was also supported for quantized matrices. In this case, you could iterate over all valid indices and get the embeddings for each index to reconstruct them.
* One other thing to consider (maybe not for this method) is whether we'd want to distinguish the whole matrix and/or just the non-subword part of it.
* What are the concrete use cases?

2019-06-04 18:06 UTC, danieldk commented on src/lib.rs
> +                StorageWrap::QuantizedArray(_) => {
In this case, you could reconstruct all the embeddings.

2019-06-04 19:07 UTC, sebpuetz commented
> Looks good. Several questions/comments:
> 
>     * It would be nicer if this was also supported for quantized matrices. In this case, you could iterate over all valid indices and get the embeddings for each index to reconstruct them.

I was just looking at the API to see if there was a method to reconstruct, I didn't dig any deeper. I'll add that!

>     * One other thing to consider (maybe not for this method) is whether we'd want to distinguish the whole matrix and/or just the non-subword part of it.

Would be nice to split the two parts but still give access to both parts. Although I'm not sure how to deal with matrices without subword embeddings.

>     * What are the concrete use cases?

Most straight forward case: feeding an embedding matrix to tensorflow instead of batching embeddings ahead of time.
Less straight forward: With the subword-part being present and by knowing the hashing function it's possible to easily check out individual subword vecs.
Way back in an A3 meeting Neele also said that it would be nice to get access to the full matrix in python.

For the matrix to be useful, we'd still need to give access to the word-idx mappings. Otherwise feeding the matrix to tensorflow doesn't make sense.

2019-06-04 19:08 UTC, sebpuetz commented
Also I'm confused by the CI failure. I locally installed rustfmt for the nightly toolchain I used to build and ran rustfmt. It reformatted some lines but apparently didn't do it in the same manner as stable rustfmt would?

2019-06-04 20:47 UTC, sebpuetz commented
I added reconstruction for the quantized storage, which means no more exceptions in python. 
I also tested the method in python, it seems to produce the expected matrices. I quantized some small model with 50 dimensions and got a matrix with 50 dimensions after calling the `matrix_copy()` method.

2019-06-04 20:56 UTC, danieldk commented
> I added reconstruction for the quantized storage, which means no more exceptions in python.

Awesome!

2019-06-05 05:53 UTC, danieldk commented
> Also I'm confused by the CI failure. I locally installed rustfmt for the nightly toolchain I used to build and ran rustfmt. It reformatted some lines but apparently didn't do it in the same manner as stable rustfmt would?

It actually uses nightly-2019-02-07, since that was the currently recommended version for pyo3.

2019-06-05 05:54 UTC, danieldk approved these changes
Looks great!

Since the module gains more and more functionality, we should probably start adding unit tests at some point.

2019-06-05 05:54 UTC, merged